name: Deploy media-service

on:
  push:
    branches: [main]
    paths:
      - "services/media-service/**"
      - ".github/workflows/deploy-media-service.yml"

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-template.yml
    with:
      service_name: media-service
      build_context: services/media-service
      ecs_cluster: streaming-musik-dev
      aws_region: ap-southeast-1
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
